Repository ifsp-projects/learning-project-webpage, pull requests merged in 2024-09, with the labels that each got.

#160 Connect supabase to project
  src/app/layout.tsx
  src/constants/headers/supabase.ts
  src/environments/supabaseAPK.ts
  src/environments/supbaseBaseUrl.ts
  src/instances/supabaseInstance.ts
  src/services/supabase/classes/index.ts
  src/services/supabase/index.ts
  src/services/supabase/lectures/index.ts
  src/services/supabase/organizations/index.ts
  src/types/utils/excludeTypeFromUnion.ts
  src/types/utils/extractArrayType.ts
Labels: Working in Progress, Feature

#195 feat(pages home): added new sections to not logged homepage
  .github/dependabot.yml
  src/app/(home)/Logged/components/MyClassrooms/ClassroomCard/index.tsx
  src/app/(home)/Logged/components/MyClassrooms/ClassroomCard/types.ts
  src/app/(home)/Logged/components/MyClassrooms/index.tsx
  src/app/(home)/Logged/components/SavedMaterials/index.tsx
  src/app/(home)/Logged/components/icons/SchoolBook.tsx
  src/app/(home)/Logged/index.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Navbar/Desktop/index.tsx
  src/styles/index.scss
Labels: Ready for Merge, Improvement

#197 Create new sections
  .env.example
  package.json
  src/app/(home)/Logged/components/MyClassrooms/index.tsx
  src/app/(user)/perfil/page.tsx
  src/app/layout.tsx
  src/assets/common/ExclamationCircle.tsx
  src/components/toolkit/Tooltip/index.tsx
  src/components/toolkit/Tooltip/types.ts
  src/components/toolkit/TooltipCursor/index.tsx
  src/components/toolkit/TooltipCursor/types.ts
  src/constants/enums/queryParameter/index.ts
  src/contexts/CroctProvider/index.tsx
  src/contexts/CroctProvider/types.ts
  src/middleware.ts
  src/middlewares/applySetCookie.ts
  src/middlewares/croct/getClientId.ts
  src/middlewares/croct/getCroctPreviewToken.ts
  src/middlewares/getCurrentUrl.ts
  src/middlewares/getHeaders.ts
  src/middlewares/hasUTMStoredMiddleware.ts
  src/utils/getters/croctEvaluate/index.ts
  src/utils/getters/croctFetchContent/index.ts
  src/utils/getters/getMiddlewareData/index.ts
  src/utils/getters/getMiddlewareData/types.ts
  src/utils/helpers/croctComponent/index.ts
  src/utils/helpers/croctComponent/types.ts
  src/utils/helpers/generateLoop/index.tsx
  src/utils/helpers/paginateArray/index.ts
  src/utils/helpers/paginateArray/types.ts
  src/utils/helpers/serializeCookie/index.tsx
  src/utils/helpers/serializeCookieData/index.ts
  src/utils/helpers/setCookieData/index.ts
  yarn.lock
Labels: Feature, Needs Discussion
