Repository ifsp-projects/learning-project-webpage, pull requests merged in 2024-07, with the labels that each got.

#4 feat(docker image) update docker image generation file
  .env.example
  .github/workflows/cd_sandbox.yaml
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: Ready for Review, Structure

#6 Add new utils and install other dependencies at project
  package.json
  src/utils/animations/motion.ts
  src/utils/getters/getFormattedCurrency/index.ts
  src/utils/getters/getMetaData/getUrlWithParams.ts
  src/utils/getters/getMetaData/index.tsx
  src/utils/getters/getRandomItem/index.ts
  src/utils/getters/getVideoId/index.ts
  src/utils/helpers/cellphoneMask/index.ts
  src/utils/helpers/cpfValidator/index.ts
  src/utils/helpers/delay/index.ts
  src/utils/helpers/generateToken/index.ts
  yarn.lock
Labels: Ready for Review, Structure

#7 Add new constants for forms
  package.json
  src/components/common/Breadcrumb/index.tsx
  src/components/toolkit/ToastMessage/index.tsx
  src/constants/app-routes.ts
  src/constants/json-cidades.ts
  src/utils/auth/bcryptjs/generateHashPassword/index.tsx
  src/utils/helpers/downloadFile/index.tsx
  yarn.lock
Labels: Ready for Review

#9 create-modal-container-component
  .github/workflows/ci.yml
  package.json
  src/app/(home)/Logged/index.tsx
  src/app/(pages)/help/page.tsx
  src/app/(pages)/messages/page.tsx
  src/app/(pages)/projects/graphic-design/page.tsx
  src/app/(pages)/projects/page.tsx
  src/app/(pages)/projects/web-design/page.tsx
  src/app/(pages)/settings/account/page.tsx
  src/app/(pages)/settings/page.tsx
  src/app/(pages)/settings/privacy/page.tsx
  src/app/layout.tsx
  src/components/common/ModalContainer/index.tsx
  src/components/common/ModalContainer/types.ts
  src/components/common/Navbar/Desktop/index.tsx
  src/components/common/Navbar/sidebar/SidebarNavigation/index.tsx
  src/components/common/Navbar/sidebar/data.tsx
  src/components/common/Navbar/sidebar/index.tsx
  src/components/common/Navbar/sidebar/types.ts
  src/hooks/use-scroll.tsx
  src/lib/utils.tsx
  yarn.lock
Labels: Ready for Review

#10 fix(sidebar) readded modal container at navbar
  src/components/common/Navbar/Desktop/index.tsx
Labels: Ready for Review

#15 feature config initial enviroments envs
  package.json
  src/app/api/upload/route.ts
  src/components/common/TextEditor/index.tsx
  src/environments/cloudinaryAPK.ts
  src/environments/cloudinaryName.ts
  src/environments/cloudinarySecret.ts
  src/environments/textEditorAPK.ts
  src/hooks/UseScroll/index.tsx
  yarn.lock
Labels: Ready for Review, Feature, Improvement

#17 inst page logged out homepage
  public/homepage/header-homepage.svg
  src/app/(home)/NotLogged/components/AboutUs/index.tsx
  src/app/(home)/NotLogged/components/Achievements/index.tsx
  src/app/(home)/NotLogged/components/Header/index.tsx
  src/app/(home)/NotLogged/components/OurServices/ServiceCard/index.tsx
  src/app/(home)/NotLogged/components/OurServices/data.tsx
  src/app/(home)/NotLogged/components/OurServices/index.tsx
  src/app/(home)/NotLogged/components/OurServices/types.ts
  src/app/(home)/NotLogged/index.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/assets/achievements/ConstantOne.tsx
  src/assets/achievements/ConstantThree.tsx
  src/assets/achievements/ConstantTwo.tsx
  src/assets/achievements/DedicatedOne.tsx
  src/assets/achievements/DedicatedThree.tsx
  src/assets/achievements/DedicatedTwo.tsx
  src/assets/achievements/Devoted.tsx
  src/assets/achievements/LockedAchievement.tsx
  src/assets/achievements/MoreThanAYear.tsx
  src/assets/achievements/Pioneer.tsx
  src/assets/achievements/Punctual.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/types.ts
  src/types/components/iconCopy.ts
Labels: Working in Progress

#38 Create admin page sections
  package.json
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/CreateClassroomModal/Form/index.tsx
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/CreateClassroomModal/Form/schemas.ts
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/CreateClassroomModal/Form/types.ts
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/CreateClassroomModal/index.tsx
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/CreateClassroomModal/types.ts
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/EditableContentCard/index.tsx
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/EditableContentCard/types.ts
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/data.tsx
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/index.tsx
  src/app/(pages)/area-do-professor/salas-de-aula/page.tsx
  src/app/layout.tsx
  src/components/common/Button/types.ts
  src/components/common/ContentCard/index.tsx
  src/components/toolkit/Fields/ErrorField/index.tsx
  src/components/toolkit/Fields/ErrorField/types.ts
  src/components/toolkit/Fields/InputField/index.tsx
  src/components/toolkit/Fields/InputField/types.ts
  src/components/toolkit/Fields/LabelField/index.tsx
  src/components/toolkit/Fields/LabelField/types.ts
  src/components/toolkit/Fields/LabelField/variance.ts
  src/components/toolkit/Fields/SelectField/index.tsx
  src/components/toolkit/Fields/SelectField/types.ts
  src/components/toolkit/Input/index.tsx
  src/components/toolkit/Input/types.ts
  src/components/toolkit/Input/variance.ts
  src/components/toolkit/Modal/index.tsx
  src/components/toolkit/SeeLessButton/index.tsx
  src/components/toolkit/SeeLessButton/types.ts
  src/components/toolkit/SeeMoreButton/index.tsx
  src/components/toolkit/SeeMoreButton/types.ts
  src/components/toolkit/Select/index.tsx
  src/components/toolkit/Select/types.ts
  src/components/toolkit/Select/variance.ts
  src/constants/errors/defaultMessageErrors.ts
  src/constants/regex/regexToGeneralEmail.ts
  src/hooks/usePagination/index.ts
  src/hooks/usePagination/types.ts
  src/utils/getters/getObjectLabel/index.ts
  src/utils/helpers/generateRandomValue/index.tsx
  src/utils/helpers/yupConfig/index.ts
  yarn.lock
Labels: Feature

#39 Next auth initial config
  package.json
  src/constants/enums/headers/index.ts
  src/constants/regex/regexToCorporateEmail.ts
  src/environments/baseUrl.ts
  src/hooks/useHandleSearchParams/index.tsx
  src/hooks/useHandleSearchParams/types.ts
  src/hooks/useIntersectionObserver/index.tsx
  src/hooks/useLockBodyScroll/index.ts
  src/hooks/useRefreshRoute/index.ts
  src/hooks/useRefreshRoute/types.ts
  src/instances/auth.ts
  src/lib/auth/credentialsOptions.ts
  src/lib/auth/index.ts
  src/middleware.ts
  src/services/auth/index.ts
  src/services/auth/users/index.ts
  src/utils/helpers/extractArrayType/index.ts
  yarn.lock
Labels: Ready for Review

#57 vitin lindo
  src/app/(pages)/termos-de-uso/page.tsx
Labels: Improvement

#60 improvement(readme) update readme content
  README.md
Labels: Ready for Review, Improvement

#59 chore(workflows) replaced npm install by yarn
  .github/workflows/ci.yml
Labels: Ready for Review, Improvement

#58 pro 22 inst page sala de aula
  public/docs/teste.pdf
  src/app/(pages)/salas-de-aula/[slug]/components/Activities/ActivityItem/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Activities/ActivityItem/types.ts
  src/app/(pages)/salas-de-aula/[slug]/components/Activities/data.ts
  src/app/(pages)/salas-de-aula/[slug]/components/Activities/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Activities/types.ts
  src/app/(pages)/salas-de-aula/[slug]/components/ClassroomNavbar/data.ts
  src/app/(pages)/salas-de-aula/[slug]/components/ClassroomNavbar/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/GeneralView/CourseDescription/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/GeneralView/CourseDescription/types.ts
  src/app/(pages)/salas-de-aula/[slug]/components/GeneralView/data.ts
  src/app/(pages)/salas-de-aula/[slug]/components/GeneralView/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Materials/MaterialCard/data.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Materials/MaterialCard/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Materials/MaterialCard/types.ts
  src/app/(pages)/salas-de-aula/[slug]/components/Materials/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Notices/MessageItem/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Notices/data.ts
  src/app/(pages)/salas-de-aula/[slug]/components/Notices/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Notices/types.ts
  src/app/(pages)/salas-de-aula/[slug]/components/Tests/TestItem/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Tests/TestItem/types.ts
  src/app/(pages)/salas-de-aula/[slug]/components/Tests/data.ts
  src/app/(pages)/salas-de-aula/[slug]/components/Tests/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Tests/types.ts
  src/app/(pages)/salas-de-aula/[slug]/components/icons/Excel.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/icons/InfoIcon.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/icons/PDF.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/icons/Word.tsx
  src/app/(pages)/salas-de-aula/[slug]/page.tsx
  src/app/(pages)/salas-de-aula/[slug]/types.ts
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/sidebar/SidebarNavigation/index.tsx
  src/components/common/Sidebar/Drawer/index.tsx
  src/components/common/Sidebar/Drawer/types.ts
  src/components/common/Sidebar/Sidebar/index.tsx
  src/components/common/Sidebar/Sidebar/types.ts
  src/styles/components/course-description.scss
  src/styles/index.scss
Labels: Working in Progress, Feature

#61 Add video player component
  .vscode/settings.json
  src/components/common/VideoPlayer/data.ts
  src/components/common/VideoPlayer/index.tsx
  src/components/common/VideoPlayer/types.ts
  src/constants/enums/cookie/index.ts
Labels: Ready for Review, Feature

#69 chore(pull_request_template) update github pr markdown
  .github/pull_request_template.md
Labels: Ready for Merge, Improvement

#74 inst-page-create-classroom-dynamic-page
  package.json
  src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/ContentContainer/index.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/Sidebar/data.ts
  src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/Sidebar/index.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/index.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/components/MobileLayout/index.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/components/icons/ArrowLeft.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/page.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/types.ts
  src/app/layout.tsx
  src/components/common/YoutubeVideoPlayer/data.ts
  src/components/common/YoutubeVideoPlayer/index.tsx
  src/components/common/YoutubeVideoPlayer/types.ts
  src/styles/components/video-player.scss
  src/styles/index.scss
  yarn.lock
Labels: Feature
