Repository ifsp-projects/learning-project-webpage, pull requests merged in 2024-08, with the labels that each got.

#84 Configure husky commit
  commitlint.config.js
  package.json
  yarn.lock
Labels: Feature

#85 project-21 inst page perfil
  src/app/(home)/NotLogged/components/Header/index.tsx
  src/app/(pages)/area-do-diretor/page.tsx
  src/app/(pages)/quem-somos/page.tsx
  src/app/(user)/perfil/components/Header/index.tsx
  src/app/(user)/perfil/components/Header/types.ts
  src/app/(user)/perfil/components/ProfileDetails/About/index.tsx
  src/app/(user)/perfil/components/ProfileDetails/About/types.ts
  src/app/(user)/perfil/components/ProfileDetails/Activities/index.tsx
  src/app/(user)/perfil/components/ProfileDetails/Activities/types.ts
  src/app/(user)/perfil/components/ProfileDetails/Activity/index.tsx
  src/app/(user)/perfil/components/ProfileDetails/Activity/types.ts
  src/app/(user)/perfil/components/ProfileDetails/Statistics/index.tsx
  src/app/(user)/perfil/components/ProfileDetails/Statistics/types.ts
  src/app/(user)/perfil/components/ProfileDetails/index.tsx
  src/app/(user)/perfil/components/icons/EmptyList.tsx
  src/app/(user)/perfil/page.tsx
  src/app/layout.tsx
  src/assets/achievements/ConstantOne.tsx
  src/assets/achievements/ConstantThree.tsx
  src/assets/achievements/ConstantTwo.tsx
  src/assets/achievements/DedicatedTwo.tsx
  src/assets/achievements/Devoted.tsx
  src/assets/achievements/Pioneer.tsx
  src/assets/achievements/Punctual.tsx
  src/components/common/Button/index.tsx
  src/components/common/Navbar/Desktop/index.tsx
Labels: Working in Progress, Institutional Page

#102 Initial config next auth at learning project
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/lib/auth/credentialsOptions.ts
  src/lib/auth/googleOptions.ts
  src/lib/auth/index.ts
  src/services/auth/types.ts
  src/services/auth/users/index.ts
  src/services/auth/users/types.ts
  src/types/auth/user.ts
  src/types/common/global.d.ts
  src/types/customEvents/common.ts
  src/types/customEvents/createCustomEvent.ts
  src/types/customEvents/customEvents.ts
  src/types/customEvents/deleteCustomEvent.ts
  src/types/customEvents/triggerCustomEvent.ts
  src/utils/auth/clearAllCookies/index.ts
  src/utils/auth/getAuthFormSearchParamsData/index.ts
  src/utils/auth/getAuthFormSearchParamsData/types.ts
  src/utils/auth/getUserSession/index.ts
  src/utils/auth/setAuthFormCookiesData/index.ts
  src/utils/auth/setAuthFormCookiesData/types.ts
Labels: Ready for Review, Feature

#114 ci(ci workflow): added new linter formatter step at ci workflow
  .github/workflows/ci.yml
Labels: Ready for Merge, Performance

#109 feat(sitemap): added sitemap builder with pages paths
  package.json
  src/constants/paths/index.ts
  src/utils/helpers/generateSitemap/generateSitemap.ts
  src/utils/helpers/generateSitemap/index.ts
  src/utils/helpers/generateSitemap/routeBuilder.ts
  src/utils/helpers/generateSitemap/staticRoutesBuilder.ts
  tsup.config.ts
  yarn.lock
Labels: Ready for Review, Feature

#121 feat(global.d.ts): added new global types
  .github/pull_request_template.md
  src/gtm/subscribeGoogleTag/index.tsx
  src/types/common/global.d.ts
  src/utils/getters/getIpAdress/index.ts
  src/utils/getters/getObjectLabel/index.ts
  src/utils/getters/getObjectLabel/types.ts
  src/utils/helpers/animateCSS/index.ts
  src/utils/helpers/generateSitemap/staticRoutesBuilder.ts
Labels: Ready for Merge, Improvement

#123 Web 12 - Create FAQ section at learning-project
  src/app/(pages)/perguntas-frequentes/components/Accordions/AccordionItem/index.tsx
  src/app/(pages)/perguntas-frequentes/components/Accordions/data.ts
  src/app/(pages)/perguntas-frequentes/components/Accordions/index.tsx
  src/app/(pages)/perguntas-frequentes/components/Accordions/types.ts
  src/app/(pages)/perguntas-frequentes/components/Header/index.tsx
  src/app/(pages)/perguntas-frequentes/components/icons/DropdownArrow.tsx
  src/app/(pages)/perguntas-frequentes/page.tsx
  src/components/common/Navbar/Desktop/index.tsx
  src/components/common/Navbar/Mobile/index.tsx
  src/hooks/useIntersectionObserver/index.tsx
  src/lib/auth/credentialsOptions.ts
  src/utils/getters/getIpAdress/index.ts
  src/utils/helpers/animateCSS/index.ts
  src/utils/helpers/generateSitemap/staticRoutesBuilder.ts
Labels: Ready for Review, Institutional Page

#127 Configure cd workflow
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  tf/main.tf
Labels: Ready for Review, Improvement

#128 ci(cd workflow): remove unused steps
  .github/workflows/cd.yml
Labels: Fix

#139 General improvements at homepage
  package.json
  public/components/logo.png
  src/app/(home)/NotLogged/components/AboutUs/index.tsx
  src/app/(home)/NotLogged/components/Header/index.tsx
  src/app/(home)/NotLogged/components/OurServices/ServiceCard/index.tsx
  src/app/(home)/NotLogged/components/OurServices/data.tsx
  src/app/(home)/NotLogged/components/OurServices/index.tsx
  src/app/(home)/NotLogged/components/SucccessCases/SuccessCaseCard/index.tsx
  src/app/(home)/NotLogged/components/SucccessCases/data.ts
  src/app/(home)/NotLogged/components/SucccessCases/index.tsx
  src/app/(home)/NotLogged/components/SucccessCases/types.ts
  src/app/(home)/NotLogged/components/WhoUseOurPlatform/SwiperSession/index.tsx
  src/app/(home)/NotLogged/components/WhoUseOurPlatform/SwiperSession/types.ts
  src/app/(home)/NotLogged/components/WhoUseOurPlatform/data.ts
  src/app/(home)/NotLogged/components/WhoUseOurPlatform/icons/ArrowLeft.tsx
  src/app/(home)/NotLogged/components/WhoUseOurPlatform/icons/ArrowRight.tsx
  src/app/(home)/NotLogged/components/WhoUseOurPlatform/index.tsx
  src/app/(home)/NotLogged/components/WhoUseOurPlatform/types.ts
  src/app/(home)/NotLogged/components/WhyUseOurPlatform/index.tsx
  src/app/(home)/NotLogged/index.tsx
  src/app/(home)/page.tsx
  src/app/(pages)/area-do-professor/salas-de-aula/Classrooms/EditableContentCard/index.tsx
  src/app/(pages)/perguntas-frequentes/components/Accordions/AccordionItem/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Activities/ActivityItem/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/ClassroomNavbar/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/GeneralView/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Notices/MessageItem/index.tsx
  src/app/(pages)/salas-de-aula/[slug]/components/Tests/TestItem/index.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/ContentContainer/index.tsx
  src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/Sidebar/index.tsx
  src/app/(user)/perfil/components/Header/index.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/common/Navbar/Desktop/icons/Notifications.tsx
  src/components/common/Navbar/Desktop/icons/User.tsx
  src/components/common/Navbar/Desktop/index.tsx
  src/components/common/Navbar/Mobile/index.tsx
  src/components/toolkit/Anchor/variance.ts
  src/components/toolkit/Button/variance.ts
  src/components/toolkit/SeeLessButton/index.tsx
  src/components/toolkit/SeeMoreButton/index.tsx
Labels: Ready for Review, Institutional Page

#140 Update platform visual
  src/app/(home)/NotLogged/index.tsx
  src/app/(pages)/perguntas-frequentes/page.tsx
  src/app/(pages)/pricing/components/Header/index.tsx
  src/app/(pages)/pricing/components/Prices/PriceCard/index.tsx
  src/app/(pages)/pricing/components/Prices/PriceCard/types.ts
  src/app/(pages)/pricing/components/Prices/data.ts
  src/app/(pages)/pricing/components/Prices/index.tsx
  src/app/(pages)/pricing/components/Prices/types.ts
  src/app/(pages)/pricing/page.tsx
  src/components/common/Navbar/Desktop/index.tsx
  src/styles/components/cta.scss
  src/styles/index.scss
Labels: Ready for Review, Institutional Page

#141 Quem somos inst page
  src/app/(home)/NotLogged/components/Header/index.tsx
  src/app/(pages)/perguntas-frequentes/page.tsx
  src/app/(pages)/quem-somos/components/Collaborators/Collaborator/index.tsx
  src/app/(pages)/quem-somos/components/Collaborators/Collaborator/types.ts
  src/app/(pages)/quem-somos/components/Collaborators/data.ts
  src/app/(pages)/quem-somos/components/Collaborators/index.tsx
  src/app/(pages)/quem-somos/components/Collaborators/types.ts
  src/app/(pages)/quem-somos/components/ConectWithUs/index.tsx
  src/app/(pages)/quem-somos/components/Header/index.tsx
  src/app/(pages)/quem-somos/components/ProvidingKnowledge/index.tsx
  src/app/(pages)/quem-somos/page.tsx
  src/components/common/Navbar/Desktop/index.tsx
Labels: Ready for Review, Institutional Page

#145 sim, mensagem
  public/homepage/header-homepage.svg
Labels: Ready for Merge, Styles
